### PR TITLE
converted old syntax to new syntax

### PR DESCRIPTION
**Pull request by assyrianic**

### CODE REVIEW

**Comment by FlaminSarge** [comment]
Has anybody made a methodmap for SDKCall handles? If so, that'd be much better to use, I think.

**Comment by assyrianic** [comment]
Sadly no but I should make a custom one!

**Comment by FlaminSarge** [comment]
Ah yeah, SDKCall() is pretty much the only thing used with those.

I was thinking of making a CEconAttribute methodmap (since tf2att returns Handles from GetByName/etc. right now) when doing the SM17 syntax conversion. Thoughts?

**Comment by assyrianic** [comment]
According to Bailopan, "delete" is basically a syntactic version of "CloseHandle"

so it's not entirely necessary to switch it out though it makes it alot easy and faster to simply type "delete Handle" or "Handle.Close()" rather than "CloseHandle(Handle)"

you can make methodmaps about damn near anything, especially if you believe it'll make it easier to code things.

**Pull request closed without merging**
